#!/bin/bash

RED="\033[1;31m"
RESET="\033[0m"

echo '      ___                       ___           ___           ___           ___     
     /\__\          ___        |\__\         /\  \         /\  \         /\__\    
    /::|  |        /\  \       |:|  |       /::\  \       /::\  \       /::|  |   
   /:|:|  |        \:\  \      |:|  |      /:/\:\  \     /:/\:\  \     /:|:|  |   
  /:/|:|  |__      /::\__\     |:|__|__   /:/  \:\  \   /::\~\:\  \   /:/|:|  |__ 
 /:/ |:| /\__\  __/:/\/__/ ____/::::\__\ /:/__/ \:\__\ /:/\:\ \:\__\ /:/ |:| /\__\
 \/__|:|/:/  / /\/:/  /    \::::/~~/~    \:\  \  \/__/ \/__\:\/:/  / \/__|:|/:/  /
     |:/:/  /  \::/__/      ~~|:|~~|      \:\  \            \::/  /      |:/:/  / 
     |::/  /    \:\__\        |:|  |       \:\  \           /:/  /       |::/  /  
     /:/  /      \/__/        |:|  |        \:\__\         /:/  /        /:/  /   
     \/__/                     \|__|         \/__/         \/__/         \/__/    '

echo

mkdir ./NixCan

echo -e "${RED}Starting Linpeas Download...${RESET}"

wget -q https://github.com/carlospolop/PEASS-ng/releases/download/20220131/linpeas.sh

echo -e "${RED}Making it executable...${RESET}"

chmod +x linpeas.sh

echo -e "${RED}Done with chmod...${RESET}"

echo -e "${RED}'Bout to run that thang...${RESET}"

bash linpeas.sh 2>/dev/null > ./NixCan/lpresults

echo -e "${RED}Sorting through all of the refuse so you don't have to...${RESET}"

echo "" > ./NixCan/output 

for i in $(cat -v ./NixCan/lpresults | grep -n "1;31;103" | grep -o '^[^:]*' | xargs) 
do
       echo $i >> ./NixCan/output

	head -n $i ./NixCan/lpresults | tail -n 1 >> ./NixCan/output
done

echo -e "${RED}Enjoy the rest of your day that we just gave back to you!${RESET}"

exit 
